### ISSUE TITLE
Add a track code that doesn't is available

### ISSUE THREAD

**Issue by gabrownx** [GabrielRF/RastreioBot#1]
Sometimes we have the tracking code that has not been updated yet in the Brazilian Post system and the bot doesnt add it to the package list. It would be interesting if the bot give us an option to add the code anyway.

**Comment by GabrielRF** [comment]
@gabrownx Entendo sua solicitação. Os problemas que consigo pensar agora, rapidamente, são:

1 - De quanto em quanto tempo o bot verificaria se o pacote tornou-se disponível no sistema dos Correios Brasileiros? Depois de quanto tempo o bot desiste?

2 - Já encontrei sistemas de rastreio "universais", que pegam códigos válidos nos Correios e códigos de outros sistemas, como aqueles chineses com mais dígitos etc. O problema é que o sistema que encontrei é pago. O RastreioBot definitivamente não é rentável, justificando o gasto da minha parte.

**Comment by gabrownx** [comment]
@GabrielRF Acredito que tenho uma resposta para a 1º: Geralmente os códigos demoram entre 3hrs-7 dias para entrarem no sistema, acredito que uma verificação a cada 3hrs enquanto o código não estiver disponível parece ser uma opção razoável e após 7 dias (ou menos) ele pergunta ao usuário se ele realmente quer continuar com esse código :package:

**Comment by GabrielRF** [comment]
Andei pensando a respeito.. Acho que encontrei uma maneira simples de resolver isso...

Ao verificar que o pacote não está na base dos correios, colocar no banco de dados assim mesmo, forçando o status do pacote para "Aguardando recebimento pela ECT" (por exemplo). O pacote seria mantido assim por 30 dias, entrando na mesma rotina que apaga os concluidos.

Se em 30 dias continuar nesse status, o pacote é apagado.
Caso ele apareça na base dos Correios, o usuário é notificado e o pacote segue normalmente no bot.

**Comment by GabrielRF** [comment]
Seria alterar este trecho: 
https://github.com/GabrielRF/RastreioBot/blob/master/rastreiobot.py#L324
Por algo semelhante ao presente a partir da linha 302, com pequenos ajustes.

**Comment by GabrielRF** [comment]
Em BETA
Commit d68d9d7ad641caa633b740b0c5e84cb4fa838288
Talvez resolva..

**Comment by gabrownx** [comment]
A solução parece adequada, essa semana receberei um pacote de fora do país. Testarei e posto aqui as minhas impressões.

**Comment by GabrielRF** [comment]
Beleza. Nos meus testes está ok. Vou fechar a issue então. Aguardo seu feedback.

**Comment by rougeth** [comment]
Valeu @GabrielRF!
