### ISSUE TITLE
Ordenar pacotes cadastrados

### ISSUE THREAD

**Issue by igorsantos07** [GabrielRF/RastreioBot#10]
Seria legal poder indicar uma ordenação dos pacotes, e ver mais detalhes na listagem do `/pacotes`:

- ordenar por pacote mais antigo, e daí, exibir tbm o número de dias desde a entrada do pacote no sistema dos Correios (ex: `- PNXXXXXXXXXNL Minha encomenda (10 dias)`)
- ordem alfabética. Eu estou usando tags (`[DX] bugigangas`) pra identificar a origem dos meus pacotes, e seria legal poder vê-los ordenados :)

**Comment by GabrielRF** [comment]
Se não me engano, ele ordena do que há mais tempo recebeu atualização para o que recebeu atualização mais recentemente, não?

**Comment by GabrielRF** [comment]
Essa issue vai dar um certo trabalho pra fechar...
Teria que mudar todo o esquema do select
Arquivo: rastreiobot.py
Linhas: 61

**Comment by igorsantos07** [comment]
Acho que não, cara... Acabei de receber um update de um pacote, mandei o
/pacotes, e esse apareceu mais ou menos no meio da lista..

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by andersonberg** [comment]
A ideia seria um novo comando, por exemplo: /pacotes_ordena e/ou /pacotes_alfa? E a ordenação dos mais antigos seria pela data de entrada do pacote no sistema dos correios ou pela data de inserção no banco do bot?

**Comment by rougeth** [comment]
Acredito que a ordenação deveria ser pela entrada do pacote nos correios, pra quem usa o bot, a data de inserção no banco do rastreiobot não faz diferença.

**Comment by andersonberg** [comment]
Beleza, comecei a trabalhar nessa issue e devo criar um PR em breve, daí vocês podem avaliar. Obrigado!

**Comment by rougeth** [comment]
@andersonberg se vc esperar até domingo pra mandar o PR, dá pra participar do [hacktoberfest](https://hacktoberfest.digitalocean.com/) :D

**Comment by andersonberg** [comment]
Ótimo, farei isso! :D

**Comment by andersonberg** [comment]
Guys, eu criei um PR pra essa issue, se puderem revisar e testar https://github.com/GabrielRF/RastreioBot/pull/15

**Comment by andersonberg** [comment]
Aceito críticas, sugestões, apelos... :D:D

**Comment by GabrielRF** [comment]
Ficou complexo pra mim.. 
@rougeth me ajuda ae!

**Comment by rougeth** [comment]
Vou tentar ver hoje a noite :D

**Comment by andersonberg** [comment]
Se quiserem posso adicionar mais comentários no código explicando a lógica. E podem ir fazendo perguntas, sem problemas.

**Comment by rougeth** [comment]
Comentários é bom, principalmente nas partes menos triviais.

**Comment by andersonberg** [comment]
Pronto, atualizei o PR com os comentários

**Comment by GabrielRF** [comment]
4ae0654d3182b6a4d41793ba6eb89daa374fd438
