### ISSUE TITLE
Pacotes não atualizam

### ISSUE THREAD

**Issue by ils15** [GabrielRF/RastreioBot#104]
O problema acontece desde ontem (05/04)
eu acredito que tenha relação com a necessidade de usar a API nova dos correios

**Comment by GabrielRF** [comment]
@ils15 Obrigado pelo aviso!
Estava tendo um problema com a API da TrackingMore, o que travou completamente a rotina de verificação.
Resolvi o problema separando em duas rotinas no commit 5fb6197.

**Comment by ils15** [comment]
Opa
que bom que deu certo
vc faz um excelente trabalho e eu divulgo seu bot no meu canal do telegram
obrigado pelo trabalho

**Comment by GabrielRF** [comment]
Eu que agradeço pelo feedback e pela divulgação!
