### ISSUE TITLE
Aviso de "não me coloque como administrador" está equivocado

### ISSUE THREAD

**Issue by luisfelipesdn12** [GabrielRF/RastreioBot#108]
## Comportamento Atual

Mesmo o bot não sendo administrador do grupo, fica mandando está mensagem toda vez que é respondido.

 ## Comportamento Esperado

Está mensagem só aparecer quando o bot é realmente admin. Em um grupo, é bem comum e útil responder os bots para comentar algo a respeito.

## Passos para reproduzir

1. Crie um grupo
2. Adicione o bot
3. Dê qualquer comando
4. Responda à mensagem enviada
5. Veja o aviso

> Extra: responda o aviso e você estrará num looping :)

## Demonstração

https://user-images.githubusercontent.com/60361387/127665207-0b3c3f33-0e82-48be-9181-fa5e5313e1d4.mp4

**Comment by GabrielRF** [comment]
Tem razão. Não havia pensando na possibilidade de alguém responder uma mensagem do bot que não fosse para o bot.
Quando é conversa da pessoa em privado com o bot é tratado. Em grupo o bot assume que não é para ele e responde isso. Irei repensar como tratar isso..

**Comment by luisfelipesdn12** [comment]
> Tem razão. Não havia pensando na possibilidade de alguém responder uma mensagem do bot que não fosse para o bot.
> Quando é conversa da pessoa em privado com o bot é tratado. Em grupo o bot assume que não é para ele e responde isso. Irei repensar como tratar isso..

Você pode verificar se é um reply pela propriedade `reply_to_message` da mensagem.
Mas afinal de contas, por que o bot não pode ser admin?

Sei que ele funciona sem ser admin, mas qual é o motivo de um aviso como esse?

**Comment by GabrielRF** [comment]
@luisfelipesdn12 Corrigido o problema. Agora ele verifica se o status do bot é ser admin mesmo.

> Por que o bot não pode ser admin? 

O problema de o bot ser admin é que 100% do que é digitado no grupo cai no histórico do bot, ficando salvo na nuvem do Telegram.
Então independente de mim ou do meu servidor, com o token do bot seria possível navegar por todas as mensagens do grupo, todo o histórico que passou pelo bot enquanto o bot foi admin. 
A fim de evitar problemas com LGPD etc, prefiro não ter esta responsabilidade de ter todas as mensagens comigo.

**Comment by luisfelipesdn12** [comment]
Pra mim, deu tudo certo, obrigado!

![image](https://user-images.githubusercontent.com/60361387/127721452-1cc3ac8f-18f3-4012-810f-ea2289dee305.png)
