### ISSUE TITLE
Migrar script del_one.py

### ISSUE THREAD

**Issue by rougeth** [GabrielRF/RastreioBot#116]
### Descrição
Criar comando para deletar um pacote no banco de dados, substituindo o script `del_one.py`. O novo comando pode ser criado no arquivo [rastreio/__main__.py](https://github.com/GabrielRF/RastreioBot/blob/master/rastreio/__main__.py).

### Requisitos para a atividade ser considerada como concluída
- [ ] Comando `rastreio packages:delete --code <package-code>` criado.
- [ ] Arquivo `del_one.py` removido.
- [ ] `README.md` atualizado com novo comando

**Comment by m1thr4nd1r** [comment]
Talvez essa issue pode ser fechada ja que o PR #133 foi mergeado?
