### ISSUE TITLE
Pacotes "abandonados"

### ISSUE THREAD

**Issue by gabrownx** [GabrielRF/RastreioBot#12]
Os Correios nem sempre atualizam os códigos de rastreio e temos anormalidades como encomendas que já foram entregues e não foram atualizados no sistema e ficam abandonados. 

Sugestão de solução: Um botão que o usuário confirma a entrega do pacote.

**Comment by GabrielRF** [comment]
Achei boa a idéia do botão. Porém, preciso fazer um pequeno estudo de como implementar isso...
Aproveitei o lembrete e fiz outra solução, a de apagar os pacotes "abandonados"..
Pacotes com 60 dias sem movimentação serão removidos da base de dados.

**Comment by GabrielRF** [comment]
Sem solução.
