### ISSUE TITLE
Falha nas atualizações

### ISSUE THREAD

**Issue by bernaction** [GabrielRF/RastreioBot#160]
O BOT parou de funcionar após, por um equívoco, tentei cadastrar um rastreio formatado em link.
Pelo celular, assim que colei o código de rastreio + descrição, o código estava embedado com link, formatado, e o BOT parou de funcionar deixando este aviso no cabeçalho do mesmo.

Tentei procurar soluções para restart mas não achei.

Att

**Comment by bernaction** [comment]
![image](https://github.com/GabrielRF/RastreioBot/assets/5149392/7ced33f9-d7fe-414f-aa75-3c3abf7d1120)

**Comment by GabrielRF** [comment]
A troca do nome foi feita por mim, para avisar as pessoas que não está atualizando.
O bot em si está ok, tudo certo.
O problema é que o servidor dos Correios parou de responder, não permitindo atualizar os pacotes.
Vou manter a issue aberta já que os Correios não mais respondem. Quando voltar, aviso aqui.

**Comment by GabrielRF** [comment]
@bernaction Problema resolvido! :smile:
