### ISSUE TITLE
Qual o problema da API?

### ISSUE THREAD

**Issue by leo-smi** [GabrielRF/RastreioBot#169]
A API bloqueou o acesso do bot?

**Comment by rafagouveia** [comment]
@leo-smi sim, segundo o post que o @GabrielRF fez, a empresa Correios revogou o acesso das chaves antigas afim de cortar custos, e dificultou a aquisição para pessoas físicas, sendo assim você tem que ser PJ e seguir uma serie de critérios que não compensa pra ele.

Você pode ler mais sobre em https://blog.gabrf.com/posts/FimDoRastreioBot/

Espero que um dia tudo volte ao normal. afinal rastrear pelos correios é a pior experiencia de usuario que já vi na terra, o próprio app deles tem um delay absurdo.

Sobre alternativas, não queria ter que mencionar mas existe um bot funcional ainda que é o https://t.me/rastreiorobot

**Comment by leo-smi** [comment]
Obrigado amigo, seguimos acompanhando e vendo no que podemos ajudar.
