### ISSUE TITLE
Faltam entradas de rastreio em alguns pacotes

### ISSUE THREAD

**Issue by igorsantos07** [GabrielRF/RastreioBot#17]
Alguns pacotes meus já foram entregues e o bot nem avisou da saída pra entrega, nem marcou como entregue.

Exemplo: PP469960207BR
Foi entregue ontem, e hoje o bot ainda tem a última informação como "encaminhado CTE Benfica".
Também tenho um Sedex no mesmo estado (OF267726308BR), mas um Sedex reverso atualizou certo hoje (foi adicionado ontem somente: DV873900982BR). 

Na sexta-feira também recebi dois Sedex que só foram atualizados como entregues pelo bot no sábado (um às 0:05 e o outro às 8:45): OF256196771BR e OF256129057BR.

**Comment by GabrielRF** [comment]
Problema a ser tratado na issue #13
