### ISSUE TITLE
Classificação de entrega finalizada incorretamente

### ISSUE THREAD

**Issue by ryukinix** [GabrielRF/RastreioBot#23]
Após uma mercadoria ser retida pela receita estadual, o objeto foi devolvido aos correios depois de alguns dias. Nessa atualização o bot classifica essa entrega como finalizada, no entanto, o processo de entrega ainda continua logo isso não deveria acontecer.

Um exemplo pode ser encontrado na encomenda: OF767272177BR.

Para essa encomenda o sumário no dia 16 de julho de 2018 dado pelo bot é:

```
📮 OF767272177BR

Data: 10/07/2018 15:38
Local: Agf Vila Pavan
Situação: Objeto postado 📦

Data: 10/07/2018 17:56
Local: Agf Vila Pavan
Situação: Objeto encaminhado ↗
Observação: Ctce Indaiatuba

Data: 10/07/2018 22:04
Local: Ctce Indaiatuba
Situação: Objeto encaminhado ↗
Observação: Ctce Fortaleza

Data: 11/07/2018 13:11 (1 dia)
Local: Ctce Fortaleza
Situação: Objeto encaminhado ↗
Observação: Avaliacao - Receita Estadual

Data: 13/07/2018 15:54 (3 dias)
Local: Cee Fortaleza
Situação: Objeto devolvido aos Correios
```

Quando o último status é processado, com a situação descrita por `Objeto devolvido aos Correios`, a entrega é classificada como finalizada pelo bot.

**Comment by GabrielRF** [comment]
@ryukinix Acredito ter resolvido o problema. 
Obrigado pelo feedback.
