### ISSUE TITLE
Add DHL tracking

### ISSUE THREAD

**Issue by patrickelectric** [GabrielRF/RastreioBot#28]

**Comment by patrickelectric** [comment]
Maybe it's possible to use this python library that provides an abstraction over 17track: https://github.com/kamushadenes/tracker17

**Comment by GabrielRF** [comment]
@patrickelectric Thank you! I'll take a look!

**Comment by TiagoDanin** [comment]
Bot worked with USPS.
![image](https://user-images.githubusercontent.com/5731176/50563949-d9b19b00-0cff-11e9-942b-5e3fd919aed6.png)
![image](https://user-images.githubusercontent.com/5731176/50563983-31e89d00-0d00-11e9-88ac-0496f60a1077.png)

**Comment by GabrielRF** [comment]
@patrickelectric Did you try to use this repo? It failed on my tests..

**Comment by patrickelectric** [comment]
will test soon, I'm in vacation right now.

**Comment by patrickelectric** [comment]
@GabrielRF 	true, it appears to be not working, will try to find any other service that provide a good tracking api.

**Comment by GabrielRF** [comment]
A ser resolvida na issue #36
