### ISSUE TITLE
Pacotes "entregues ao destinatário" mas que ainda recebem atualizações

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/RastreioBot#30]
Há pacotes que recebem o status "Entregue ao destinatário" e continuam recebendo atualizações no sistema dos Correios.
Tal situação ocorre em casos, por exemplo, em que o pacote é devolvido ou o endereço estava incorreto.

A rotina de verificação pula em casos de pacotes entregues. Não acho que seja o caso de simplesmente parar esse salto, uma vez que iria aumentar e muito o número de verificações, principalmente em pacotes concluídos. 

Os pacotes concluídos são mantidos no bot por alguns dias (30, se não me engano), logo, verificar também pacotes já marcados como entregues aumentaria muito a carga do bot. 

Sugestões?

**Comment by AtilioA** [comment]
Não sei se há alguma solução prática pra isso, uma vez que ser marcado como entregue pelos Correios já é um erro.

Talvez pudesse haver uma verificação menos frequente nos itens concluídos, tornando-os "ativos" novamente caso tenha ocorrido uma atualização, possivelmente com um aviso ao usuário que o pacote ainda está ativo.

**Comment by licensed** [comment]
Na minha opinião, é dever do usuário monitorar se não foi entregue e adicionar novamente o mesmo pacote.

**Comment by GabrielRF** [comment]
@licensed O usuário não conseguiria fazer isto uma vez que o pacote permanece no bot por 30 dias após ser entregue. Então o envio do código de rastreio apenas resultaria no histórico do pacote..

**Comment by licensed** [comment]
@GabrielRF ah, entendi meu amigo.
Mesmo que o erro seja dos correios, acho importante tentarmos achar uma solução pra isso.
Mas no momento não consigo pensar em nenhuma idéia.

**Comment by GabrielRF** [comment]
9d9373d75e5ad491f3e98253e2f31ff57acd0e30
