### ISSUE TITLE
Facilitar a cópia do código de rastreamento

### ISSUE THREAD

**Issue by felipecrs** [GabrielRF/RastreioBot#33]
Isso é interessante pois hoje para copiar um código de rastreamento a partir de um texto (de status por exemplo), é necessário copiar todo o corpo, colar numa caixa de texto, fazer a seleção do código e por fim copiar. Uma das formas de fazer isso seria formatando como mono espaçado o `código de rastreamento`. Isso funciona no Telegram para Android (clica sob o `texto mono espaçado` e ele é automaticamente é copiado). Um exemplo de uso seria para quando alguém encaminha um status proveniente do RastreioBot para alguma conversa e outra pessoa quer adicionar o tal pacote no seu RastreioBot também.

**Comment by guilhermecomum** [comment]
Essa isse não deveria ser fechada pela #32 ?

**Comment by felipecassiors** [comment]
O #32 adicionou a feature de detectar o código de rastreamento de mensagens encaminhadas. Esse issue se refere a possibilidade de tornar mais fácil a cópia do código de rastreamento, que pode ser útil para outras coisas.

**Comment by felipecassiors** [comment]
Agora no Telegram para Android é possível selecionar um trecho de uma mensagem facilmente. Alguém com iOS poderia testar se também foi adicionado essa feature?
