### ISSUE TITLE
Trocar formato da data

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/RastreioBot#35]
https://github.com/GabrielRF/RastreioBot/blob/892de3a701705c97c69923c1a3eb27e552509ae0/apitrackingmore.py#L35

Formato atual: `2019-09-10 12:36:00`
Formato desejado: `10/09/2019 12:36`

**Comment by TiagoDanin** [comment]
Nice! :+1:

**Comment by luizpericolo** [comment]
Posso trabalhar nessa!

**Comment by GabrielRF** [comment]
@luizpericolo Obrigado pela ajuda! 
Tentei contato contigo pelo Telegram, mas não consegui :disappointed:
