### ISSUE TITLE
Documentação para rodar a aplicação e contirbuir com o projeto.

### ISSUE THREAD

**Issue by maurobaraldi** [GabrielRF/RastreioBot#41]
Atualmente com a documentação existente não é possivel rodar a aplicação, pois há alguns dados que são esperados no arquivo `bot.conf`, como informações sobre o acesso aos correios,  que não estão disponíveis na documentação.

Consequentemente não é possivel contrinuir com o projeto. :-(

**Comment by maurobaraldi** [comment]
Encontrei [esse](http://blog.correios.com.br/correioslog/wp-content/uploads/2017/12/Correios-Web-Service-Padr%C3%B5es-T%C3%A9cnicos-de-Comunica%C3%A7%C3%A3o-do-Servi%C3%A7o-e-fulfillment_v2-5.pdf) documento. É valido!?

**Comment by GabrielRF** [comment]
@maurobaraldi Vou corrigir o README e o bot.conf_sample.. Obrigado por observar isso
Sobre os Correios, o documento ficava disponível em https://www.correios.com.br/para-voce/correios-de-a-a-z/pdf/rastreamento-de-objetos/manual_rastreamentoobjetosws.pdf, mas aparentemente sumiu!

**Comment by GabrielRF** [comment]
@maurobaraldi Ficou bom?
