### ISSUE TITLE
Atualizar requirements.txt 

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/RastreioBot#42]
Há coisas que não são mais utilizadas no `requirements.txt`.
Seria interessante também atualizar algumas versões.

**Comment by rougeth** [comment]
O que você acha de usar algo como `poetry` ou `pipenv`?

**Comment by GabrielRF** [comment]
@rougeth São excelentes

**Comment by rafaelgotts** [comment]
Acho que já pode fechar essa issue, certo?

**Comment by richardnixonafj** [comment]
> O que você acha de usar algo como `poetry` ou `pipenv`?

resolveram só atualizar o arquivo?

**Comment by rafaelgotts** [comment]
Eita. Eu achei que poderia ser uma sugestão ou outra issue... #PeçoPerdãoPeloVacilo 🙈
