### ISSUE TITLE
Encontrar o código de rastreio em qualquer lugar da mensagem

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/RastreioBot#43]
Atualmente é necessário enviar o código seguido da descrição, por exemplo.
Acho que seria uma boa o bot identificar o código independente de onde esteja.. 
Exemplo:
O bot funcionaria com 
```
AB123456789CD teste
```
e com
```
Teste AB123456789CD
```
Ou ainda com 
```
Teste1 AB123456789CD Teste2
```
Sendo tudo o que não for o código de rastreio considerado descrição do pacote.

**Comment by anaschwendler** [comment]
Oi @GabrielRF posso tentar pegar essa issue?
Você poderia me dar mais contexto sobre como planeja que isso seja feito?

Valeu 🎉

**Comment by GabrielRF** [comment]
@anaschwendler Claro que pode!

É o seguinte.. Atualmente o bot aceita somente a mensagem no formato 
`código descrição`
Porém, há muitos casos em que as pessoas enviam, por exemplo, 
`descrição código`
Então acho que seria legal se o bot fosse capaz de se virar com isso..

**Comment by anaschwendler** [comment]
@GabrielRF dale, vou tentar aqui!
