### ISSUE TITLE
Apagar pacotes

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/RastreioBot#5]
Não vejo muita utilidade uma vez que caso você tenha o código de rastreio pode-se entender que o pacote seja seu. 
Idéias/Sugestões?

**Comment by rougeth** [comment]
E em casos de input errado do usuário?

**Comment by GabrielRF** [comment]
O usuário tem que errar o código dele e acertar outro... 
Muito provavelmente vai dar a mensagem de pacote não recebido pelos Correios, ou seja, em 30 dias o pacote é apagado automaticamente caso ele não entre no sistema.

**Comment by rougeth** [comment]
É mais fácil ele simplesmente mandar outro né?

**Comment by mateusc-ciandt** [comment]
@GabrielRF no meu caso, o pacote foi entregue mas o sistema dos correios ainda continua falando que o pacote está em transito rs, isso já faz mais de 30 dias... creio que essa feature de apagar ou marcar como entregue seria ótima!

**Comment by mateusc-ciandt** [comment]
LX355820754CN

**Comment by indiocabrunco** [comment]
Boa tarde pessoal.
Estive me deparando com o problema de entrada errada, e acabei parando aqui, vi até que tem uma função del_one, mas não vi nenhuma chamada manual pra ela.
Realmente, como podem ver, fica um registro errado, o que numa lista grande se torna incomodo.
Entendo que por um lado, se torna ruim por conta de qualquer usuário eventualmente poder apagar qualquer pacote mesmo não sendo dele, mas cabe cada um adicionar novamente se for o caso. A não ser que dê pra colocar uma restrição de alteração somente para o usuário que adicionou o pacote.
Mas no todo, achei muito bom o projeto, parabéns!

![rastreiobot](https://user-images.githubusercontent.com/31077016/29378380-3e321be6-8295-11e7-9c1a-2ce265b6f81e.JPG)

**Comment by GabrielRF** [comment]
@indiocabrunco Fala comigo no Telegram que eu apago para você.
