### ISSUE TITLE
/Comando

### ISSUE THREAD

**Issue by ThigSchuch** [GabrielRF/RastreioBot#6]
Atualmente o Bot funciona com 3 botões (Pacote - Info - Concluídos)
Ambos possuem uma barra ( / ) antes dos nomes, visualmente isto fica estranho, seria melhor retirar ela e deixar os botões mais limpos.

**Comment by rougeth** [comment]
@ThigSchuch usando a `/` nos comandos, é possível configurar as sugestões de comandos no botfather. Quando você digita só `/` é possível ver todas as opções possíveis.

**Comment by ThigSchuch** [comment]
Sim, eu sei, mas não estou falando pra tirar a / dos comandos, e sim dos botões que aparecem no bot

**Comment by rougeth** [comment]
@ThigSchuch o problema nisso é que o texto que ta no botão é o mesmo que é enviado quando se clica nele. O que daria pra fazer é bot responder o comando sem e com `/`.

**Comment by GabrielRF** [comment]
Seria uma gambiarra sem fim pra tirar essa barra.
O botão que permite exibir uma coisa e enviar outra é o InlineKeyboardButton, mas mudaria a UX do bot.

**Comment by indiocabrunco** [comment]
Bom dia pessoal.
Estava analisando, e se entendi a conversa, fica minha opinião leiga.
Creio que tirar a barra seria fácil se o bot utilizasse aquele formato de botões ao invés de lista de comandos. Quando é uma lista de comandos, acho que é padrão todos eles mostrarem barra como segue na primeira imagem.
Não sei se da pra colocar em grupo aquele botão como nas outras 2 imagens que estou enviando.
Sei também que sem como mudar para uma # por exemplo, mas nunca vi listar isso como na primeira imagem que mandei, limitando os comandos a serem executados sem esse "atalho" na lista.
Reforço que sou leigo, então só estou expondo o que observo, mas não sei quanto as aplicações em bot.

![barras em todos os bots em grupos](https://user-images.githubusercontent.com/31077016/29776911-94a83f92-8be0-11e7-84a0-3fbfb05e7ce5.jpg)
![Botão para botões](https://user-images.githubusercontent.com/31077016/29776909-94a3410e-8be0-11e7-8803-cfca0d20d28e.jpg)
![Botões](https://user-images.githubusercontent.com/31077016/29776910-94a7712a-8be0-11e7-8997-ef32f47611a7.jpg)

**Comment by GabrielRF** [comment]
@indiocabrunco São coisas diferentes. 
O que o RastreioBot usa é o ReplyKeyboardMarkup, que entra no lugar do teclado.
O que aparece no meio do texto, como os botões de coração, são InlineKeyboard. 
No caso do RastreioBot eu não sei se ficaria legal a substituição...

**Comment by indiocabrunco** [comment]
Me referia aos botões de baixo, não o InLineKeyboard nas mensagens.
E também foi só pra tentar ilustrar alguma coisa do que entendi da sugestão do ThigSchuch.
Pra mim o bot esta de boa com relação a isso.

**Comment by GabrielRF** [comment]
Quando o bot é usado em privado, ou seja, fora de grupos, ele dá o ReplyKeyboardMarkup.
![ReplyKeyboardMarkup](https://user-images.githubusercontent.com/7331540/29783105-817968aa-8bf5-11e7-8f06-3bb3850cb7a2.png)
Essa opção foi removida de grupos a pedido dos usuários, pois o povo se confundia quando o teclado "sumia" para eles.

**Comment by GabrielRF** [comment]
Sem solução
