### ISSUE TITLE
Configurar coverage no Travis

### ISSUE THREAD

**Issue by rougeth** [GabrielRF/RastreioBot#61]
- [ ] Adicionar biblioteca `coverage` ao requirements.txt;
- [ ] Configurar Travis para executar `coverage` após testes;
- [ ] Ideia: falhar testes se cobertura diminuir, ou seja, fazer PR sem testes. Isso pode adicionar uma barreira para quem for contribuir, mas ao mesmo tempo, traz segurança em aceitar novas contribuições.

**Comment by richardnixonafj** [comment]
Falha todos os testes? ou deve ser criado um somente pra essa finalidade?

**Comment by rougeth** [comment]
Opa, @richardnixonafj acho que não ficou claro o que eu falei. O Travis marca o PR como ok se todos os testes passarem, certo? Com a proposta dessa issue, se para um determinado PR a cobertura de testes diminuir, mesmo com todos os testes existentes passando, a build no Travis deveria falhar, marcando o PR como **não ok**. O que você acha?

**Comment by richardnixonafj** [comment]
Foi o que eu pensei! vou trabalhar nesta Issue!

**Comment by richardnixonafj** [comment]
@rougeth pode verificar se seria isso ?
