### ISSUE TITLE
Melhorias para a contagem de dias

### ISSUE THREAD

**Issue by igorsantos07** [GabrielRF/RastreioBot#7]
- [x] quando a contagem está abaixo de 2 dias, a palavra aparece no plural (ex: `1 dias`)
- [ ] a contagem só é atualizada quando há novos updates sobre o pacote. Exemplo: `Data: 22/08/2017 09:39 (1 dias)`; aqui deveria dizer 6 dias, na verdade.

**Comment by GabrielRF** [comment]
Não entendi o segundo caso.
Você gostaria que ele contasse os dias até hoje?

**Comment by GabrielRF** [comment]
8b15d44dfddf4ecfb2efceb49bf6004d579884f8

**Comment by indiocabrunco** [comment]
Gabriel, acho que entendi o que ele informou.
No print que segue, note que mandei o comando agora (dia 28/08/2017) e a ultima atualização foi do dia 23/08/2017, mas o dia contado esta informando (1 dia)... mas de 23 para 28 não é 1 dia de diferença.

![print](https://user-images.githubusercontent.com/31077016/29777651-23c7c20e-8be3-11e7-9753-442046fdd1bd.jpg)

**Comment by GabrielRF** [comment]
Mas 1 dia refere-se a diferença do dia 22 para o dia 23..

**Comment by igorsantos07** [comment]
Sim, mas isso não fica óbvio, eu acho..
 E, no fundo, não me soa muito relevante saber o tempo desde o último
update, mas sim há quanto tempo o pacote tá tramitando.

Mas talvez seja só pra mim, sei lá :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]
