### ISSUE TITLE
Compilar regex que são usadas multiplas vezes

### ISSUE THREAD

**Issue by rougeth** [GabrielRF/RastreioBot#79]
A função `check_type` usa regex para identificar que tipo de código o usuário envia (correios vs aliexpress). Já que as expressões regulares são usada multiplas vezes, podemos compilá-las fora da função e reusá-las.

https://github.com/GabrielRF/RastreioBot/blob/master/misc.py#L13-L25

**Comment by kfcaio** [comment]
Não consigo abrir o link aqui, recebo 404

**Comment by GabrielRF** [comment]
O `misc` foi pra dentro de uma pasta agora
https://github.com/GabrielRF/RastreioBot/blob/master/utils/misc.py

**Comment by andersonberg** [comment]
Eu posso trabalhar nessa issue, se não for problema

**Comment by rougeth** [comment]
@andersonberg manda a ver :)
