### ISSUE TITLE
Mensagens mais limpas

### ISSUE THREAD

**Issue by igorsantos07** [GabrielRF/RastreioBot#8]
Sugeriria remover as labels de alguns dos campos, pois o texto deles é autoexplicativo; isso torna as mensagens mais limpas, de leitura mais fácil e fluida.

Atualmente:
>📮 RSxxxxxxxxxNL
>
>Data: 07/08/2017 18:14
>Local: PAISES BAIXOS
>Situação: Objeto encaminhado ↗️
>Observação: Unidade de Tratamento Internacional
>
>Data: 21/08/2017 14:42 (14 dias)
>Local: UNIDADE INTERNACIONAL CURITIBA
>Situação: Objeto recebido pelos Correios do Brasil
>
>Data: 24/08/2017 14:22 (17 dias)
>Local: CENTRO INTERNACIONAL PR-GEINT
>Situação: Objeto encaminhado ↗️
>Observação: CTE BENFICA

Sugestão:
>📮 RSxxxxxxxxxNL
>
> 07/08/2017 18:14
> ↗️ Objeto encaminhado (PAISES BAIXOS)
>Observação: Unidade de Tratamento Internacional
>
> 21/08/2017 14:42 (14 dias)
> Objeto recebido pelos Correios do Brasil (UNIDADE INTERNACIONAL CURITIBA)
>
> 24/08/2017 14:22 (17 dias)
>↗️ Objeto encaminhado (CENTRO INTERNACIONAL PR-GEINT)
>Observação: CTE BENFICA

## _Bonus points_
- [x] é correto afirmar que o local é onde o pacote está, e a obs é pra onde ele está sendo encaminhado, sempre? Se sim, o texto poderia ser algo como `<situação> de <local> para <obs>`, ou:
```
<situação>
De <local>
Para <obs>
```
- [x] seria legal acertar o _case_ do local (ex: de `PAISES BAIXOS` para `Paises Baixos`)

**Comment by GabrielRF** [comment]
Não é possível afirmar que o campo `observação` corresponde ao destino. Exemplo:

```
Data: 18/07/2017 09:11
Local: CENTRO INTERNACIONAL PR-GEINT
Situação: Objeto encaminhado ↗️
Observação: Brasil - Liberado sem Tributação RFB 
```

**Comment by GabrielRF** [comment]
Vou perguntar para outros usuários essa questão da mensagem mais limpa..

**Comment by GabrielRF** [comment]
7d0f7e3d11106746f1a172da4b853e98aa13d334

**Comment by igorsantos07** [comment]
De fato! O Muambator na verdade assume isso mas se perde no exemplo que
você deu hehe

**Comment by igorsantos07** [comment]
De fato! O Muambator na verdade assume isso mas se perde no exemplo que você deu!

![screenshot_2017-08-28-19-54-05](https://user-images.githubusercontent.com/532299/29937981-a04ba2ce-8e5d-11e7-8ac4-58266212c387.jpg)
