### ISSUE TITLE
Remover mensagens malformadas é realmente benéfico?

### ISSUE THREAD

**Issue by AtilioA** [GabrielRF/RastreioBot#90]
Me refiro à modificação do commit ff527ab506ef789414d71d7fbfc2df7f38d6b177. Creio que seja uma modificação desnecessária e que não traz benefícios.

Alguns pontos:
- Nenhum comando do bot depende de argumentos, portanto a modificação não "livraria" um usuário leigo de um problema de ficar clicando no atalho de `/comando` sem saber como usar o comando (não sei se deu pra entender);
- O usuário não tem oportunidade de aprender com o erro, pois a mensagem é instantaneamente apagada;
- É um tanto agressivo e invasivo. Pessoalmente, fiquei surpreso quando percebi a funcionalidade;
- O conteúdo da mensagem é perdido: se o usuário trouxe um código de rastreio de outra aplicação (por uma ação de _share_ que seja), por exemplo, a informação é perdida e o usuário terá que obter o código novamente (copiando para a área de transferência). 
- Não vejo problema em manter uma mensagem malformada/inadequada no histórico;

**Comment by GabrielRF** [comment]
Respondendo diretamente o título: Não sei.

As pessoas tendem a enviar as coisas mais aleatórias possíveis para o bot. Chega absolutamente de tudo. Não adianta falar, explicar e dar exemplos. Vem login e senha, fotos pessoais e mais um monte de coisa. 
Sabendo que com o `token` do bot é possível ver todas as mensagens que já passarem pelo bot, julguei que apagar a mensagem seria o que me daria a menor dor de cabeça.
Minha intenção era evitar problemas com LGPD e afins, uma vez que a mensagem apagada não pode ser recuperada. 

Talvez eu não tenha feito da melhor forma possível, mas foi a melhor idéia que tive. heheh
Obviamente estou aberto a sugestões! :)
